#!/bin/sh
# Runs inside the docs (Ruby/Python) container.
# Model docs are pre-generated by the docs-model init container (php artisan docs:model).
set -e

cd /workspace

echo "Generating commit documentation..."
python3 scripts/generate-commit-docs.py

echo "Starting Jekyll..."
cd /workspace/docs
exec bundle exec jekyll serve --host 0.0.0.0 --watch --force_polling
